### ISSUE TITLE
serverless-plugin-browserifier & serverless-plugin-typescript

### ISSUE THREAD

**Issue by kvarela** [digitalmaas/serverless-plugin-browserifier#9]
I'm experiencing an error on `sls package` trying to have both of these plugins active in my project. It appears to be looking for my .serverless dir inside my .build dir, even though they are both at the root of my project. If I run either plugin without the other, everything works fine. Any ideas how to fix?

Here's the end:
```
Serverless: Packaging service...

  Error --------------------------------------------------

  ENOENT: no such file or directory, lstat '/Users/home/roam/backend/.build/.serverless'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: ENOENT: no such file or directory, lstat '/Users/home/roam/backend/.build/.serverless'
    at PluginManager.invoke (/Users/home/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/Users/home/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/Users/home/.config/yarn/global/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/Users/home/.config/yarn/global/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/home/.config/yarn/global/node_modules/serverless/bin/serverless:43:50)
```

**Comment by nolde** [comment]
Hello @kvarela !

I was under the impression -- considering our exchange in https://github.com/digitalmaas/serverless-plugin-browserifier/issues/8 -- that everything was now working as expected. Are you still having problems?

Regarding the issue at hand, I wouldn't expect this two plugins to work together anyway. They both meddle with serverless' packing steps, and should not be used together.  As you have said yourself, it works fine by itself, so I do not consider this to be a bug.

Therefore, I am closing this issue. I will not spend time troubleshooting interaction with other plugins with clearly conflicting behaviour. I'll gladly help you get this working by using this plugin and `tsify`, though, if you are willing to explore this option further.
